### ISSUE TITLE
C++ wrapper header a la vulkan.hpp

### ISSUE THREAD

**Issue by rpavlik** [KhronosGroup/OpenXR-SDK-Source#131]
Tracking issue for an "openxr.hpp"

I've done some work on this related to trying things out with symbol loading and dispatch. It's now pretty good (partially based on the code from Vulkan.hpp, but not sharing generation code), but still has gaps.

Here's the (generated code that I committed) header: https://github.com/rpavlik/OpenXR-SDK-Source/blob/openxr-hpp/include/openxr/openxr.hpp

Generation uses scripts/templates in here: https://github.com/rpavlik/OpenXR-SDK-Source/tree/openxr-hpp/src/scripts

FWIW, the doxygen output for the header is currently actually pretty reasonable.

I should probably split this into a separate repo, but it arose as a bit of a hack so it didn't start from blank.

cc @jherico

**Comment by jherico** [comment]
I've updated my [branch](https://github.com/jherico/OpenXR-SDK-Source/tree/openxr-hpp) to contain

* enhanced flag bits and flag types
* enhanced C++ structs (CompositionLayerQuad instead of XrCompositionLayerQuad)
* updated two-call idiom methods to reflect the use of the enhanced structure types
* special-cased xrEnumerateSwapchainImages to require an additional template parameter for the graphics-API specific structure type so you can do this:  
  * `auto swapchainImages = swapchain.enumerateSwapchainImages<xr::SwapchainImageVulkanKHR>();`

Next issues to tackle

* two-call idiom broken for functions that provide enums (`xrEnumerateEnvironmentBlendModes`, etc...)
* Generate a proper hierarchy, at least for SwapchainImageXXX and CompositionLayerXXX based classes
* improve templating of enumerateSwapchainImages to generate a compile time error if user tries to fetch a vector of a type that is not derived from `SwapchainImageBaseHeader`

**Comment by jherico** [comment]
two-call idiom fixed for enum result types.  Next most valuable issue would probably be structure returns...

    auto instanceProperties = _xr.instance.getInstanceProperties();

instead of 

    xr::InstanceProperties ip;
    _xr.instance.getInstanceProperties(ip);

**Comment by rpavlik** [comment]
Closing since we now have https://github.com/KhronosGroup/OpenXR-Hpp/
