### ISSUE TITLE
SDK Android support 

### ISSUE THREAD

**Issue by androidzhibinw** [KhronosGroup/OpenXR-SDK-Source#156]
would you add Android support ?

**Comment by rpavlik** [comment]
We'd probably merge Android support if submitted, but I'm not aware of any public plans in the working to port it.  Personally I have tried to build it with the NDK, and it gets part of the way but not all the way.

The OpenXR API does contain support for Android already, it is only these SDK pieces that don't.

**Comment by BattleAxeVR** [comment]
This bug was opened over two years ago and still not completed. Why is that? Do you consider Android compatibility not worth supporting or something?

For anyone who needs to run this sample on Android (to save some time googling), you can refer to this repo:

https://github.com/daj/OculusHelloXR

Honestly, I don't understand why this isn't fixed already Ryan. Please consider prioritizing this (or just merge the code), it's frankly a waste of time to have to look elsewhere than the official repo to run hello_xr on Android on the most popular HMD on the market today in native standalone mode.

This isn't the first time I've had issues with your sample not being maintained properly, if it's not fixed I will escalate it with your superiors.

**Comment by rpavlik** [comment]
So this is enabled now, there is a cross-vendor loader in this repo, and the last two releases have both had Android artifacts attached. I'm not sure where Oculus is on adopting/supporting the cross-vendor loader, but other vendors do.

**Comment by BattleAxeVR** [comment]
In that case, it's just a documentation issue, as there are no Android build instructions in the README and I still had to waste time googling a solution.

**Comment by BattleAxeVR** [comment]
I'm not talking about the loader but the hello_xr app, which is the entire reason for this repo's existence.
