### ISSUE TITLE
Cannot open include file "common/xr_linear.h" in hello_xr

### ISSUE THREAD

**Issue by zurgeg** [KhronosGroup/OpenXR-SDK-Source#204]
I was working on a game for the Oculus Rift S through OpenXR and it errors out in VS 2019 with 2 errors:
1. `Cannot open include file "common/xr_linear.h"`
2. `'OutputDebugStringA': identifier not found`
Can anyone help fix this? Thanks in advance.
EDIT: Oculus and Steam are installed, though it is notable that when running Microsoft's example, it simply doesn't do anything. Could there be no detected runtimes?

**Comment by rpavlik** [comment]
This looks like a compile issue rather than a runtime issue, so what runtimes you have installed shouldn't matter. 

Part 1 looks like you don't have your include paths set right. How are you setting up the build? VS2019 has support for CMake so you should be able to "open folder" with VS2019 on this repo and have everything work right.

Part 2 - you're missing an include. `OutputDebugStringA` is a Windows API call, so it required `#include "Windows.h"`

Do you see these issues with a fresh clone of this repo? or only with your modified code?

**Comment by zurgeg** [comment]
I fixed it and forgot about this issue.
