### ISSUE TITLE
XR_KHR_opengl_enable requires protected XrGraphicsBindingOpenGLXlibKHR type

### ISSUE THREAD

**Issue by aeikum** [KhronosGroup/OpenXR-SDK-Source#216]
The `XR_KHR_opengl_enable` extension lists `XrGraphicsBindingOpenGLXlibKHR` as a required type. However, this type has `protect="XR_USE_PLATFORM_XLIB"`, while the extension has `protect="XR_USE_GRAPHICS_API_OPENGL"`. So, the extension may require a type which is unavailable.

I can work around this by ignoring required types which are not defined, but I thought I'd bring it to your attention, as it seems like a bug in the spec. If it isn't, feel free to close.

**Comment by rpavlik** [comment]
I think the spec explains that you need both a graphics API define as well as a platform define: so to use XrGraphicsBindingOpenGLXlibKHR , you need to define both `XR_USE_PLATFORM_XLIB` and `XR_USE_GRAPHICS_API_OPENGL`.

I think your interpretation of the XML/spec is not quite the same as the intent:  the extensions list types **provided**, not **required** (despite less than ideal element naming we inherited - "require" is a signal to the header generator, etc. that generating an extension requires generating the given list of definitions).  The "protect" just indicates which ifdefs to wrap a definition in, when it's being generated. So, all the definitions of the extension are wrapped in the graphics API ifdef, and some of the definitions are further protected by an additional ifdef for platform.  See here: https://github.com/KhronosGroup/OpenXR-SDK/blob/master/include/openxr/openxr_platform.h#L89  The outer ifdef is the protect attribute on the extension, while individual generated declarations are wrapped in their platform protections.

I suspect based on this issue that you're using your own code for parsing and code-gen based on the XML, is that right? Did this help you understand things a bit better? The XML is mainly intended for consumption by the WG-maintained set of tools, but it is possible to consume it externally too. (There is a relax-ng schema in the tree, but it doesn't answer questions like this.) You might look at Vulkan for details on the schema, since the OpenXR schema is mostly a subset of the Vulkan one, and our tooling is largely shared. Our WG hasn't seen fit to invest in more custom documentation given that the Vulkan schema is well documented and essentially the same. https://www.khronos.org/registry/vulkan/specs/1.2/registry.html

**Comment by aeikum** [comment]
Thanks @rpavlik . I agree this was my misunderstanding the spec. Closing.
