### ISSUE TITLE
Please include .so versioning

### ISSUE THREAD

**Issue by luyatshimbalanga** [KhronosGroup/OpenXR-SDK-Source#221]
Will it possible to incorporate a versioning for .so files when building a package? Here is a patch below addressing the issue.

[openxr-1.0.12-soversion.patch.txt](https://github.com/KhronosGroup/OpenXR-SDK-Source/files/5507055/openxr-1.0.12-soversion.patch.txt)

Thanks in advance

**Comment by rpavlik** [comment]
We certainly can, actually surprised we don't have it already, since I packaged this for Debian.

Oh, the layers. Those are more like plugins than "proper" (linked-against, loaded implicitly by dynamic loader) shared libraries. We could add a soname, but I don't know what would use it, and it would be somewhat meaningless. (The OpenXR loader loads those based on .json metadata manifest files, and they normally aren't installed in the LD_LIBRARY_PATH.)

Can you elaborate on what you'd use an API layer soname for so I can understand the use case better?

**Comment by luyatshimbalanga** [comment]
Sorry for the late reply. I am a Fedora package maintainer where the reviewers requested to add the so version. Unfortunately I do not have a Khronos account.

**Comment by rpavlik** [comment]
No problem, I wasn't suggesting you get a khronos account. That's just what my script does when I sync GitHub issues over to the private gitlab to make sure they get viewed.

I did the packaging for Debian, so I know how we did it there to get it through review. In debian, we're installing the layers to a different directory - a subdir of the library directory - because they're never loaded automatically by the dynamic linker. They're only loaded explicitly by the "loader" library (via dlopen after finding them with the manifest). Since they don't really expose an interface to link against, it didn't make sense to me to have an soversion. The loader itself has a soversion, of course.

For example the apidump layer gets installed to:

`/usr/lib/x86_64-linux-gnu/openxr/1/api_layers/libXrApiLayer_api_dump.so`

I have applied a patch in the Debian package (which I should probably upstream to myself) that mangles the JSON manifest filename with the architecture, and include an absolute path to the so file: This allows multiple architectures to have their json files installed in /usr/share without conflicting. The loader will just ignore manifests for so files it can't load. so, the corresponding manifest file is:

`/usr/share/openxr/1/api_layers/explicit.d/XrApiLayer_api_dump.x86_64-linux-gnu.json`

(in the amd64 build - see https://packages.debian.org/sid/amd64/openxr-layer-apidump/filelist )

The patches I'm referring to are:

- https://salsa.debian.org/openxr-team/openxr-sdk-source/-/blob/debian/sid/debian/patches/0009-On-Linux-make-the-API-layer-manifest-have-an-absolut.patch
- https://salsa.debian.org/openxr-team/openxr-sdk-source/-/blob/debian/sid/debian/patches/0010-Mangle-API-layer-manifest-filename.patch

Sorry, I am unfamiliar with the Fedora packaging rules. If I understand properly, this suggests it might not be needed because the API layers are effectively plugins: https://docs.fedoraproject.org/en-US/packaging-guidelines/#_downstream_so_name_versioning and probably more specifically here: https://docs.fedoraproject.org/en-US/packaging-guidelines/#_devel_packages

> As an additional complication, some software generates unversioned shared objects which are not intended to be used as system libraries. These files are usually plugins or modular functionality specific to an application, and are not located in the ld library paths or cache. This means that they are not located directly in /usr/lib or /usr/lib64, or in a directory listed as a library path in /etc/ld.so.conf (or an /etc/ld.so.conf.d/config file). Usually, these unversioned shared objects can be found in a dedicated subdirectory under /usr/lib or /usr/lib64 (e.g. /usr/lib/purple-2/ is the plugin directory used for libpurple applications). In these cases, the unversioned shared objects do not need to be placed in a -devel package.

The API layers work pretty similarly to the Vulkan validation layers. However, it looks like the Vulkan validation layer package on Fedora has them installed directly in `%{_libdir}/libVkLayer_*.so` which is not what I was told to do (by mostly debian packaging experts) for the layers in OpenXR, and which appears to contradict the guideline I quoted above.

Thanks for your work on packaging this. Does this help at all? I'd suggest dropping the patch you added and instead using something like the two I linked. FYI we did just release a new patch release, 1.0.14, yesterday. I haven't gotten around to packaging it for Debian yet either.

**Comment by rpavlik** [comment]
Oh, looking at https://src.fedoraproject.org/rpms/openxr/blob/master/f/openxr.spec - you will probably also want to package the two README files in the API layers directory. On Debian, we actually have the layers packaged separately from the loader, since the layers won't be used by most people (basically, they're development tools, just like the Vulkan ones). The binary packages we have on debian are:

- libopenxr-dev - the headers installed to /usr/include/openxr, the cmake config and pkgconfig files
- libopenxr-loader1 - the loader so itself.
- libopenxr-utils - the two executables (hello_xr and openxr_runtime_list)
- openxr-layer-apidump
- openxr-layer-corevalidation

Here are the files each package contains (on AMD64):

- libopenxr-utils
  - `usr/bin/hello_xr`
  - `usr/bin/openxr_runtime_list`
  - `usr/share/doc/libopenxr-utils/changelog.Debian.amd64.gz`
  - `usr/share/doc/libopenxr-utils/changelog.Debian.gz`
  - `usr/share/doc/libopenxr-utils/changelog.gz`
  - `usr/share/doc/libopenxr-utils/changelog.html.gz`
  - `usr/share/doc/libopenxr-utils/copyright`
  - `usr/share/man/man1/hello_xr.1.gz`
  - `usr/share/man/man1/openxr_runtime_list.1.gz`
- openxr-layer-apidump
  - `usr/lib/x86_64-linux-gnu/openxr/1/api_layers/libXrApiLayer_api_dump.so`
  - `usr/share/doc/openxr-layer-apidump/changelog.Debian.amd64.gz`
  - `usr/share/doc/openxr-layer-apidump/changelog.Debian.gz`
  - `usr/share/doc/openxr-layer-apidump/changelog.gz`
  - `usr/share/doc/openxr-layer-apidump/changelog.html.gz`
  - `usr/share/doc/openxr-layer-apidump/copyright`
  - `usr/share/doc/openxr-layer-apidump/README_api_dump.md`
  - `usr/share/lintian/overrides/openxr-layer-apidump`
  - `usr/share/openxr/1/api_layers/explicit.d/XrApiLayer_api_dump.x86_64-linux-gnu.json`
- openxr-layer-corevalidation
  - `usr/lib/x86_64-linux-gnu/openxr/1/api_layers/libXrApiLayer_core_validation.so`
  - `usr/share/doc/openxr-layer-corevalidation/changelog.Debian.amd64.gz`
  - `usr/share/doc/openxr-layer-corevalidation/changelog.Debian.gz`
  - `usr/share/doc/openxr-layer-corevalidation/changelog.gz`
  - `usr/share/doc/openxr-layer-corevalidation/changelog.html.gz`
  - `usr/share/doc/openxr-layer-corevalidation/copyright`
  - `usr/share/doc/openxr-layer-corevalidation/README_core_validation.md.gz`
  - `usr/share/lintian/overrides/openxr-layer-corevalidation`
  - `usr/share/openxr/1/api_layers/explicit.d/XrApiLayer_core_validation.x86_64-linux-gnu.json`
- libopenxr-dev
  - `usr/include/openxr/openxr_platform_defines.h`
  - `usr/include/openxr/openxr_platform.h`
  - `usr/include/openxr/openxr_reflection.h`
  - `usr/include/openxr/openxr.h`
  - `usr/lib/x86_64-linux-gnu/cmake/openxr/OpenXRConfig.cmake`
  - `usr/lib/x86_64-linux-gnu/cmake/openxr/OpenXRConfigVersion.cmake`
  - `usr/lib/x86_64-linux-gnu/cmake/openxr/OpenXRTargets-none.cmake`
  - `usr/lib/x86_64-linux-gnu/cmake/openxr/OpenXRTargets.cmake`
  - `usr/lib/x86_64-linux-gnu/libopenxr_loader.so`
  - `usr/lib/x86_64-linux-gnu/pkgconfig/openxr.pc`
  - `usr/share/doc/libopenxr-dev/changelog.Debian.amd64.gz`
  - `usr/share/doc/libopenxr-dev/changelog.Debian.gz`
  - `usr/share/doc/libopenxr-dev/copyright`
- libopenxr-loader1:
  - `usr/lib/x86_64-linux-gnu/libopenxr_loader.so.1`
  - `usr/lib/x86_64-linux-gnu/libopenxr_loader.so.1.0.13`
  - `usr/share/doc/libopenxr-loader1/changelog.Debian.amd64.gz`
  - `usr/share/doc/libopenxr-loader1/changelog.Debian.gz`
  - `usr/share/doc/libopenxr-loader1/changelog.gz`
  - `usr/share/doc/libopenxr-loader1/changelog.html.gz`
  - `usr/share/doc/libopenxr-loader1/copyright`
  - `usr/share/lintian/overrides/libopenxr-loader1`

(For what it's worth, we package the Monado OpenXR runtime in our arch-specific lib search path, even though it logically shouldn't have a soversion either: this is so that we can have the same manifest file on both architectures `usr/share/openxr/1/openxr_monado.json`, and let the dynamic linker find the right architecture of runtime: `usr/lib/x86_64-linux-gnu/libopenxr_monado.so`  I do think this was an exception to the Lintian policy checker, though. We could go with a soversion of 1 for the Monado OpenXR runtime since it is used by a 1.0 OpenXR loader, though just like with the layers, nobody looks at the soversion of the runtimes because they're drivers. Yes, I'm a co-maintainer of Monado upstream, too.)

**Comment by rpavlik** [comment]
btw found a bug in the package description, I think:

```

%description devel
--
  | Development files for the USD library. Install this package if you
  | want to compile applications using the OpenXR library.

```

USD is probably not actually what's meant there.

**Comment by luyatshimbalanga** [comment]
> The API layers work pretty similarly to the Vulkan validation layers. However, it looks like the Vulkan validation layer package on Fedora has them installed directly in `%{_libdir}/libVkLayer_*.so` which is not what I was told to do (by mostly debian packaging experts) for the layers in OpenXR, and which appears to contradict the guideline I quoted above.
> 
Fedora packaging guideline has more simple guideline: unversioned .so goes to -devel unless they are plugins as quoted while versioned are assigned to libs. Maybe updating the cmake to fix the path will help.

> Thanks for your work on packaging this. Does this help at all? I'd suggest dropping the patch you added and instead using something like the two I linked. FYI we did just release a new patch release, 1.0.14, yesterday. I haven't gotten around to packaging it for Debian yet either.

Yes it does. I received the notification about the new release and will update the package. 

> %description devel
> --
>   | Development files for the USD library. Install this package if you
>   | want to compile applications using the OpenXR library.
> ```
> 
> USD is probably not actually what's meant there.

Good catch, I fixed that mistake.
Thank you the help and explanation.

**Comment by rpavlik** [comment]
As discussed, the API layer .so files are plugins, like the vulkan validation layers https://src.fedoraproject.org/rpms/vulkan-validation-layers/blob/rawhide/f/vulkan-validation-layers.spec , so it does not make sense to put a soname on them. Let me know if there's some way I can help you revise your package to package those layers separately - though to be fair, they're probably of most interest to developers (just like the vulkan validation layers) so it's probably mostly harmless to have them the way they are now. Please do include the two README files (and associated images) for the layers, though. They're fairly hard to use without docs.

**Comment by luyatshimbalanga** [comment]
Thanks, which README file do I need to look other than README.md in the parent directory?

**Comment by rpavlik** [comment]
The readme files in the API layer directory.
