### ISSUE TITLE
Hello_xr runs at 64-67 FPS on Quest 2 using Oculus Runtime, when set to 90 Hz.

### ISSUE THREAD

**Issue by BattleAxeVR** [KhronosGroup/OpenXR-SDK-Source#227]

**Comment by philpax** [comment]
I can confirm this behaviour in both a real application and `hello_xr`. `xrWaitFrame` takes a considerable amount of time on the Oculus runtime, resulting in 60-70 FPS. Using the SteamVR runtime results in a near-solid 90 FPS.

Optick Oculus trace, where `vr::PreTick` is just `xrWaitFrame`:
![image](https://user-images.githubusercontent.com/707827/106386715-78061280-642a-11eb-9201-43a64889fecd.png)

Optick SteamVR trace, 12ms frame (outlier, probably due to some frame timing adjustment required on my part)=
![image](https://user-images.githubusercontent.com/707827/106386784-c3b8bc00-642a-11eb-8d44-32010ffff86d.png)

**Comment by BattleAxeVR** [comment]
I don't have access to the Khronos page so no idea what the status is on this yet, Philpax.

It's disheartening that this bug hasn't been fixed yet, considering I opened it on Nov 20th. 

Oculus' official OpenXR runtime is basically unusable on Quest 2 due to this show-stopper bug. I haven't tested SteamVR's runtime recently, but their runtime was also buggy on Quest 2 the last I tried. 

For development, having to manually reset the view each time I start up the app is a serious productivity drain and a major nuisance. So currently neither runtime actually works properly yet and it looks like I will have to buy a WMR headset so I can actually test OpenXR.

It would seem logical to me if Oculus would send a sample Quest 2 to Ryan here so he can reproduce these problems first-hand, and see the sorry state of affairs of OpenXR on Oculus headsets on PC. Honestly this is getting beyond frustrating to me now, it's actually going to prevent me from being able to release my game on schedule.

**Comment by BattleAxeVR** [comment]
I created a new report in the OpenXR developer forums section:

https://forums.oculusvr.com/developer/discussion/98224/oculus-openxr-runtime-issue-prevents-90-hz-on-pc

**Comment by BattleAxeVR** [comment]
This is with latest OpenXR SDK source, latest developer Oculus software (v25 something), and latest Vulkan SDK (on latest Nvidia drivers as of today).

![image](https://user-images.githubusercontent.com/11604039/106393839-3abc6900-63c7-11eb-878f-60d93e530ce9.png)

**Comment by BattleAxeVR** [comment]
I checked in Unreal, and it runs at 90 FPS without issue. So the bug is here.

![image](https://user-images.githubusercontent.com/11604039/106815775-55e6dd00-6642-11eb-8492-65026a1dd2d8.png)

**Comment by BattleAxeVR** [comment]
03/02 17:27:15.003 {WARNING} [OXR] OXRSessionData::WaitFrame adjusting predictedDisplayTime from 177299201114656 to 177299201114658

I wonder if this is the cause of the problem.

**Comment by BattleAxeVR** [comment]
To recap, guys. This particular issue isn't runtime-specific, but implementation specific. Which is in your perview to fix. You'll need an Oculus headset to reproduce and fix it. Something's not right with the way hello_xr interacts with Oculus' swap chains.

I'm going to try and fix this issue myself and will post the solution. But since Unreal runs at 90 FPS while hello_xr (and implementations such as mine which used this as a template) do not, therefore the bug is in the implementation (probably). I don't really care where the bug is, maybe Unreal's plugin simply doesn't manifest the runtime bug. But a workaround is all I need. I need this to work properly.

**Comment by bradgrantham-lunarg** [comment]
Hi, @BattleAxeVR !

I've just verified that my WinMR headset here runs at a rock solid 90Hz in hello_xr.  That seems to point at this issue not being with the SDK.  In any case, the SDK doesn't do anything different for any particular HMD or OpenXR runtime.

The OpenXR SDK can be thought of as a thin layer of functions that call the vendor's runtime on the application's behalf (and taking care of a lot of bookkeeping so the application doesn't have to), as well as a sample program, "hello_xr".

That is to say, the OpenXR SDK is basically doing this (simplified e.g. ignoring API layers):

```
XrResult xrWaitFrame(...) {  // This function is in the loader
    return runtime->WaitFrame();  // The implementation of this call is provided by the vendor's runtime.
}
```

It's a lot like Direct3D on Windows calling the driver provided by a vendor.  When you say "implementation", the "implementation" in this case is from Facebook.  The OpenXR SDK doesn't "interact" or do anything with swapchains except pass them back to the app, or from the app back to the runtime.

(SteamVR is a special case, since _as I understand it_ Valve's OpenXR implementation may be calling the non-OpenXR Oculus libraries.)

You can review the source for hello_xr and the SDK (primarily the loader, which calls the vendor's runtime on behalf of your app) to verify this.  Both are in this repository.  I think you'll find that the code in the SDK in xrWaitFrame between your app and the OpenXR runtime amounts when the application is running to little more than taking your function parameters and calling another function in a DLL that the OpenXR loader has loaded.

If you have identified a bug with the loader, or incompatible versions of the header, or a specification typo, this repo is a good place to open an issue.

But this isn't the right place to ask about a Quest performance problem.  Since Facebook authored their OpenXR runtime, they certainly have run hello_xr themselves.  So they may know about this issue and possibly how to fix it.  I don't know why there hasn't been any visible progress on your issue in the Facebook Oculus developer forum, but you won't have much luck here in OpenXR-SDK-Source because OpenXR contributors reading these are focused on SDK issues.

**Comment by BattleAxeVR** [comment]
From my perspective: the difference between hello_xr and Unreal plugin IS an SDK issue: both call the exact same runtime dll, but in a different sequence and with different timings, and Unreal runs at 90 FPS on Oculus HMDs while hello_xr doesn't. That's the bottom line for me. A reference implementation should run correctly on all SKUs it purports to support, and if it doesn't, bugs should be opened, tracked, and fixed. I attempted to do so here and in Oculus forums (with no success after several months), so I give up. I just needed something that works. Anyway, I found my solution: I'll start over and base my own XR integration off Unreal's instead. Have a nice day. Closing...

**Comment by BattleAxeVR** [comment]
For anyone interested, Oculus shared the workaround with me after I raised it on their forums here:

https://forums.oculusvr.com/developer/discussion/comment/788028

You need to call timeBeginPeriod(1) before initializing anything else on Windows. 

Unreal does so in WindowsPlatformMisc.cpp (587) and a few other places, like for audio.

Oculus told me they will be adding this call internally in v27 of their runtime but there's no harm in calling it multiple times so I'm going to leave it in my code.
