### ISSUE TITLE
OpenXR SDK does not compile on Windows without `XR_USE_GRAPHICS_API_D3D11`/similar

### ISSUE THREAD

**Issue by philpax** [KhronosGroup/OpenXR-SDK-Source#237]
Hi there! This is a fairly minor issue, but it caused me a little grief recently. I've been integrating the SDK into a non-DX codebase using a different build system and used a minimal set of defines to add Windows support:
```
'API_NAME="OpenXR"',
"XR_USE_TIMESPEC",
"XR_CURRENT_API_MAJOR_VERSION=1",
"XR_CURRENT_API_MINOR_VERSION=0",
"XR_CURRENT_API_PATCH_VERSION=13",
"XR_USE_GRAPHICS_API_OPENGL",
"XR_USE_PLATFORM_WIN32", 
"XR_OS_WINDOWS", 
"WIN32", 
"_WINDOWS", 
```

However, this will not compile. `openxr/openxr_platform.h` refers to `IUnknown`, which isn't pulled in by `xr_dependencies.h` with the above set of defines. Defining the D3D defines pulls in the DX headers, which in turn pulls in the headers for `IUnknown`.

Again, really minor, but might save someone else in the same predicament some trouble 😅

**Comment by brycehutchings** [comment]
I think in this case IUnknown is required because of XR_MSFT_perception_anchor_interop and XR_MSFT_holographic_window_attachment. These extensions actually use IUnknown to avoid putting a dependency on a more specific type. I think the minimum include would be <unknwn.h>, if that is available in your build system. I think we consider IUnknown a core type to the Win32 build, and since D3D uses IUnknown, the type is brought in by defining XR_USE_GRAPHICS_API_D3D11/XR_USE_GRAPHICS_API_D3D12.

**Comment by philpax** [comment]
Yep, that's right; my suggestion is to pull `unknwn.h` into `xr_dependencies.h` if `WIN32` is defined. I didn't want to change the XR files so I left it as-is, but that should work fine (assuming that there are no other implicit dependencies).

**Comment by rpavlik** [comment]
Yeah, for some reason our headers aren't being generated with the external `#include` lines despite being marked up with them in XML. Not sure why you've found something different with the d3d stuff - presumably because you're using the (mess of an internal) header xr_dependencies. Seems like a reasonable thing to add to there.

**Comment by rpavlik** [comment]
OK, I've put up a fix to review.

**Comment by amalon** [comment]
This issue also appears to affect users of the OpenXR headers, not just the loader itself. Somebody on the flightgear mailing list reported it with MSVC 2019 (16.11.18), with OpenXR 1.0.24:
https://sourceforge.net/p/flightgear/mailman/message/37697116/
Visual studio community 2022 didn't seem affected. Including unknwn.h before openxr_platform.h worked around it, but it seems flawed to expect openxr apps to anticipate includes that might be required on windows for extensions they don't use or future extensions they may not know about.

Should the openxr_platform.h header not include unknwn.h itself?

**Comment by rpavlik** [comment]
so that's a good question. The required headers/includes are marked up in the XML but aren't being written to the header files for some reason. Can you open an issue for adding those includes to openxr_platform.h? It is annoying to work around for sure.
