### ISSUE TITLE
Add the `bitwidth` XML attribute for parity with the Vulkan XML specification

### ISSUE THREAD

**Issue by Perksey** [KhronosGroup/OpenXR-SDK-Source#258]
Vulkan, where there are enums/bitmasks that occupy more or less than 64 bits, defines a `bitwidth` attribute like so:
```xml
<enums name="VkPipelineStageFlagBits2KHR" type="bitmask" bitwidth="64">
    <!-- ... -->
</enums>
```

For Silk.NET's OpenXR bindings, we reuse the our Vulkan XML parser which depends on this attribute to treat an enum as not 32-bit. Because this attribute isn't present in OpenXR, any usage of `XrFlags64` currently is treated as 32-bit.

This is partially our fault and we're working on fixing this in our bindings, but this issue is to once again make OpenXR's XML spec consistent with that of Vulkan.

**Comment by rpavlik** [comment]
Our schema is based on the Vulkan one when the WG started, but it's not exactly the same. As you noticed, all our flags are 64 bit, but there are additional differences (see the schema in the repo for details). I'm not sure specifying this would help much, but if e.g. @oddhack  thinks it's a good idea I'm not opposed.

**Comment by oddhack** [comment]
There's minor downside in cluttering your XML with something you don't use, but minor upside in keeping the schema closer. If you think it's something you want to add and keep up going forward (which might be as simple as a schema validation rule to ensure it's present?), go for it.

We run into this a lot on Vulkan where somebody doing a downstream project consuming the XML wants augmentation of the schema to supply information that's irrelevant to Khronos' needs. One concern is that anything we don't use, is not likely to be well maintained.

**Comment by Perksey** [comment]
You're absolutely right. I suppose before we do this we could do with a XML linting tool (which is something I'm happy to do before taking this further, though my time for the next 6 or so months is extremely constrained, because let's be honest Khronos don't need to maintain XML augments so why should they make the maintenance tools)

When I have time (in the mid-term future), I'll get in touch before continuing on this issue's proposal so we can get the validation rules in place before adding stuff. Happy for this to be assigned to me in the meantime.

**Comment by rpavlik** [comment]
We have an XML schema for linting: https://github.com/KhronosGroup/OpenXR-Docs/blob/master/specification/registry/registry.rnc  This gets tested in CI. It's based on the Vulkan one, but somewhat re-written to simplify it and make it stricter.

I also added Schematron recently for a few things I couldn't easily test with relax-ng: https://github.com/KhronosGroup/OpenXR-Docs/blob/master/specification/registry/registry.sch

and there's higher-level checks in xml-consistency: https://github.com/KhronosGroup/OpenXR-Docs/blob/master/specification/scripts/xml_consistency.py

It probably would reduce complexity of our shared scripts, they wouldn't have to know that OpenXR assumes 64 bit flags, so that's probably worth it right there actually. We can race: If I get it done before I hear from you, I'll let you know so you don't waste any time.

**Comment by rpavlik** [comment]
So our flags are 64 bit, perhaps, but our enums are 32, which I didn't realize...

**Comment by rpavlik** [comment]
OK, I have submitted a merge request internally ( https://gitlab.khronos.org/openxr/openxr/-/merge_requests/2186 ). It won't make it in time for the next release, but should be in the following one if the WG has no opposition. The patch includes updating the OpenXR relax-ng schema to require bitwidth="64" so it will stay up to date.

**Comment by rpavlik** [comment]
The WG has opted not to merge the change. I didn't actually find any place in our scripts that would be simplified by including this. They wanted to avoid the additional clutter, and would prefer a way to set a default. I assume that you've presumably worked around this in your use case by now?
