### ISSUE TITLE
Clarification needed for Android loader AAR location and usage

### ISSUE THREAD

**Issue by Izhido** [KhronosGroup/OpenXR-SDK-Source#293]
For version 1.0.22, the Release notes contain the following text:

> The Android loader can be found on Maven Central, by adding the following line to your Android app's build.gradle dependencies section:
> 
> `implementation 'org.khronos.openxr:openxr_loader_for_android:1.0.22'`

However, checking Maven Central as of Jan 29, 2022, there is no package corresponding to version 1.0.22, only for 1.0.20.

Also, there is no clear explanation on how, for a CMake project that uses OpenXR-SDK (instead of OpenXR-SDK-Source), one would go to include and use the proposed Android loader. Additional documentation is needed for existing projects to stop using the vendor-supplied loader and start using the new loader.

**Comment by rpavlik** [comment]
Hmm. GitHub was supposed to have pushed that automatically. Looks like maybe it was still on manual, oops. I kicked it off now.

Does your cmake project get built by gradle? If so, just use the artifact that way. It gets exposed to CMake (via prefab) just like on desktop: find_package(OpenXR), OpenXR::Loader, etc. Otherwise let me know a bit more about how you're building so I can help.

(The files used by the loader are in both -sdk and -sdk-source repos, and you can see the cmake and gradle scripts in there to see how it builds.)

**Comment by rpavlik** [comment]
OK, those jobs finished. I think it should show up on Maven Central soon - there's a little bit of a promotion delay.

**Comment by rpavlik** [comment]
Ah, I did have to manually poke it. I've updated my instructions. Let me know about your build system and I'll see how I can help.

**Comment by utzcoz** [comment]
> OK, those jobs finished. I think it should show up on Maven Central soon - there's a little bit of a promotion delay.

1.0.22 shown up on maven: https://search.maven.org/artifact/org.khronos.openxr/openxr_loader_for_android/1.0.22/aar.

**Comment by tongweizhou** [comment]
@rpavlik 
When I use the build.gradle in the [androidteapots](https://gitlab.freedesktop.org/monado/demos/androidteapots) project .mavenCentral(), implementation'org.khronos.openxr:openxr_loader_for_android:1.0.22'.

Cmake Build Can not find openx.cmake.
**ErrorMessage**:
  Could not find a package configuration file provided by "OpenXR" with any
  of the following names:
   OpenXRConfig.cmake
   openxr-config.cmake


The actual Cmake is here
. /classic-teapot/.cxx/cmake/debug/prefab/armeabi-v7a/prefab/lib/arm-linux-androideabi/cmake/OpenXR/OpenXR-config.cmake

I had to write a Find*.cmake to Fix it.

**Comment by rpavlik** [comment]
oh... I wonder if that's a bug in the teapot app (I never finished it), or if it's due to an old version of prefab. There were some issues regarding capitalization in older versions of the prefab tool used by the android gradle plugin.  (I do also have a FindOpenXR.cmake script in https://github.com/rpavlik/cmake-modules/blob/main/FindOpenXR.cmake which should be compatible, but should not be needed in this case because of all the prefab magic they're doing...)

**Comment by utzcoz** [comment]
@rpavlik What about adding aar dependency usage for Android to Loader spec?

**Comment by rpavlik** [comment]
I'm planning a presentation and blog post in the next few weeks
