### ISSUE TITLE
maintainer-scripts/build-aar.sh has undocumented 7za dependency

### ISSUE THREAD

**Issue by fredinfinite23** [KhronosGroup/OpenXR-SDK-Source#303]
When building the loader with mainainer-scripts/build-aar.sh, '7za' is used without checks and this happened on my side (debian/ubuntu-impish): 
"./maintainer-scripts/build-aar.sh: line 54: 7za: command not found"

'7za' constitues an external dependency that is not documented at the moment.

Resolution:
 I had to manually install that p7zip-full on my system and build resumed just fine.

**Comment by rpavlik** [comment]
That entire script is undocumented at the moment.

**Comment by rpavlik** [comment]
That script is not intended for people who are not maintainers of this repo, but as of the 1.0.28.2 hotfix, we've switched to using the jar tool and there is documentation at the top of that script.

Hopefully nobody needs to run that script outside of the working group processes and CI, though, since we are trying to get vendors to converge on being compatible with our standard cross-vendor loader artifacts as-shipped.
