### ISSUE TITLE
XR_FB_space_warp extension not present

### ISSUE THREAD

**Issue by aboitreaud** [KhronosGroup/OpenXR-SDK-Source#361]
I am using OpenXR SDK to develop a PC VR app with Oculus Quest 2 in cable link (quest link). I have enabled the OpenXR runtime in the Oculus app and the developer mode that gives additional openXR extensions. 
When logging the available extensions, I get 37 extensions. Some of them are XR_FB_... or XR_OCULUS_...
However, I get the following error when I try to use XR_FB_space_warp extension:
```
Error [GENERAL | xrCreateInstance | OpenXR-Loader] : LoaderInstance::CreateInstance, no support found for requested extension: XR_FB_space_warp
Error [GENERAL | xrCreateInstance | OpenXR-Loader] : xrCreateInstance failed
[16:06:23.692][Error  ] XrResult failure [XR_ERROR_EXTENSION_NOT_PRESENT]
```
I am using v46.0 for Oculus app and OpenXR SDK 1.0.24, which shloud be ok since XR_FB_space_warp is apparently supported from OpenXR SDK 1.0.23.
Could you give me a hint about on to make this missing extension available ? Thanks

**Comment by rpavlik** [comment]
The extensions that are available on a given runtime differ. SDK support for an extension just means that it includes the documentation, headers, etc. for that extension, not that any particular runtimes support it. In particular, the extensions available on a Quest 2 over link cable can and do differ from those available when running directly on the Quest, because it is two different runtimes, and Meta has not chosen to make all the same functionality available, as far as I know.

There is crowd-sourced information on extensions available in different runtimes at https://github.khronos.org/OpenXR-Inventory/extension_support.html There is not (yet) a listing explicitly for quest 2 over link cable, but I think it works effectively like the entry for "Meta (PC)"
