### ISSUE TITLE
Broken docker link in "Building the OpenXR Specification" page

### ISSUE THREAD

**Issue by dgough** [KhronosGroup/OpenXR-SDK-Source#476]
The URL to the docker file in [Building the OpenXR Specification](https://github.com/KhronosGroup/OpenXR-SDK-Source/blob/main/specification/README.md) is broken. I assume it is supposed to be:

https://github.com/KhronosGroup/DockerContainers/blob/main/openxr-sdk.Dockerfile

Also, the instructions mention `open-in-docker.sh`, but I don't see that anywhere.

**Comment by rpavlik** [comment]
Good catch, yes we did rename that file a while back. (the one you linked is actually for SDK build, not for the spec build.) The images are pushed to docker-hub however.

Since those docs (and the container) are intended for spec build, the open-in-docker script is only in the docs repo (as well as the private Khronos monorepo): https://github.com/KhronosGroup/OpenXR-Docs/blob/main/open-in-docker.sh

Since we do have the loader doc in this repo, I suppose it might make sense to ship it in this one too, I'll adjust that for the next release.

**Comment by rpavlik** [comment]
OK, I have an internal MR to fix the docs and ship the script in this repo too, I anticipate it will be merged for the next release.

**Comment by rpavlik** [comment]
Fixed in 1.1.37, thanks for the report!
