### ISSUE TITLE
hello_xr

### ISSUE THREAD

**Issue by TheArchKnight** [KhronosGroup/OpenXR-SDK-Source#6]
Hi, i have compiled and installed the SDK, and actually i had installed the headers. When i try to compile the helo_xr example, i get an error from this line(openxr_program.cpp):

`#include <common/xr_linear.h>`

The paths are rigt, as VSCode get the autocomplete when writing the line.
Should i be missing something?

**Comment by TheArchKnight** [comment]
Had get it working by moving the common folder to the example folder, but now i have another issue, and its that it drops:
` #error Unsupported platform or no XR platform defined!
`
From platformplugin_factory.cpp file 

it seems that it dont be able to know if im using Xorg.
A weird issue!

**Comment by remmel** [comment]
> Had get it working by moving the common folder to the example folder, but now i have another issue, and its that it drops: `#error Unsupported platform or no XR platform defined!` From platformplugin_factory.cpp file
> 
> it seems that it dont be able to know if im using Xorg. A weird issue!

As you can read in the code above https://github.com/KhronosGroup/OpenXR-SDK-Source/blob/b15ef6ce120dad1c7d3ff57039e73ba1a9f17102/src/tests/hello_xr/platformplugin_factory.cpp#L34 this is because the platform has ne been set.
For example on Android,`XR_USE_PLATFORM_ANDROID` must be set, using for example in `CMakeList.txt` `add_definitions(-DXR_USE_PLATFORM_ANDROID)`
In that hello_xr, it is set automatically in a parent `CMakeList`.txt https://github.com/KhronosGroup/OpenXR-SDK-Source/blob/b15ef6ce120dad1c7d3ff57039e73ba1a9f17102/src/CMakeLists.txt#L276

**Comment by rpavlik** [comment]
My guess is that you ran CMake in something other than the root folder of the repository. Those platform definitions occur higher in the tree.
