### ISSUE TITLE
VisualStudio should prefer std::filesystem to std::experimental::filesystem

### ISSUE THREAD

**Issue by daveh-lunarg** [KhronosGroup/OpenXR-SDK-Source#77]
VS has long had a bug with incorrect setting of __cplusplus macro, which causes the loader (and potentially other projects) to select the `experimental` flavor of std::filesystem. This [blog post](https://devblogs.microsoft.com/cppblog/msvc-now-correctly-reports-__cplusplus/) describes how to force VS2017 to report an accurate __cplusplus value.

The cmake .sln generator should be updated to add the two required compiler switches (`/Zc:__cplusplus` and `/std:c++17`)

**Comment by daveh-lunarg** [comment]
std::filesystem on VS requires VS2017 v 15.7 or later (`_MSC_VER >= 1914`) and `/std:c++latest`.

**Comment by yl-msft** [comment]
@daveh-lunarg   the current configuration in filesystem_utils.cpp is to USE_FINAL_FS when c++17 or higher, and fallback to DISABLE_STD_FILESYSTEM if otherwise.   The __cplusplus configuration is not useful for MSC.

```
#if defined(_HAS_CXX17) && _HAS_CXX17
// When MSC supports c++17 use <filesystem> package.
#define USE_EXPERIMENTAL_FS 0
#define USE_FINAL_FS 1
#endif  // !_HAS_CXX17
```

I think this solution is good enough, and we've been running with this setting (with c++17 or not) extensively and works fine for both win32 and UWP platforms on Hololens.
